### ISSUE TITLE
ListGroupItem throwing errors from Linkable

### ISSUE THREAD

**Issue by jabez007** [inkline/inkline#124]
* **I'm submitting a:**

  - [x] Bug Report
  - [ ] Feature Request
  
* **What is the current behavior?**

After upgrading to version 1.20.1 the ListGroupItem component throws several 
> Property or method is not defined on the instance but referenced during render

errors that seem to stem from the Linkable component that is being extended

* **What is the expected behavior?** (If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** viahttps://plnkr.co or similar.)

Not throw errors

I was able to stop the errors by changing the Linkable index.vue file to
```
<template src="./template.html" />

<script>
  import Linkable from './script.js';

  export default Linkable;
</script>
```

why does the above not throw an error over the current
```
<script src="./script.js" />
<template src="./template.html" />
```

I don't know

* **Please tell us about your environment:**

  - Version: 1.20.1
  - Browser: [Chrome | Firefox]
  - Language: [TypeScript X.X | ES6/7 | ES5]

* **Other information** (Detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc.)

**Comment by jabez007** [comment]
Also, v.1.19.0 appears to be the last version that does not throw these errors

**Comment by alexgrozav** [comment]
Looking into it now. Thank you for letting me know!

**Comment by alexgrozav** [comment]
I wasn't able to reproduce it, but I think I know what's causing it. I've released 1.20.2 with a fix. Can you try it out and confirm that it's working now?

**Comment by jabez007** [comment]
Yeah, it looks like it might have actually been more of an issue of out of date dependencies in my project.

I updated Inkline to  v1.20.2 and was still getting the same errors, but then I updated the Vue CLI plugin for Babel to v4.1.0 and got it working.
