### ISSUE TITLE
Clearable icon is displayed on initial load with blank input

### ISSUE THREAD

**Issue by five1** [inkline/inkline#352]
* **Expected behavior**
  The clearable icon is only visible if there is text to remove from the input box. Example: The [Microsoft Bing search input box](https://www.bing.com/search?q=clearable) only shows a clearable icon when text is present in the input box.

* **Current behavior**
  The clearable icon is visible even if there is no text in the input box. It only occurs on initial load. If text is typed and then deleted or cleared, the clearable icon is not shown. This is inconsistent behaviour.

* **Steps to reproduce**
  Render an [input box with the clearable property set](https://www.inkline.io/docs/forms/input#clearable-variant).
`<i-input v-model="value" clearable placeholder="Type something.." />`

* **Please tell us about your environment:**
    - Version: >=3.2.0
    - Browser: Chrome 111.0.5563.66 (Official Build) (64-bit) | Firefox 111.0.1 (64 bits) | Edge 111.0.1661.51 (Official build) (64-bit)
    - Language: TypeScript

**Comment by alexgrozav** [comment]
@five1 Thank you for reporting the issue. Can you try the latest release please? I've made some changes to how slots are rendered in SSR and this should be fixed as well.

**Comment by five1** [comment]
@alexgrozav I have tried version 4.0.0. It has not fixed this issue.

Also, in version 4.0.0:
- the blue-50 background was not being applied, but I was able to change it to primary
- I was forced to correct bottom margins for some elements
- the search icon `(<i-button class="_background:primary _color:light">
                      <i-icon name="ink-search" />
                  </i-button>)` is not displayed and the button is very wide and not active. However, the mouse pointer does change when hovering. (see screenshot and HTML snippet attached)
                 <img width="399" alt="Inkline 4 search box" src="https://github.com/inkline/inkline/assets/7004707/e00c075d-5ff5-4140-8b97-1e486aa2a6ab">
                  [Inkline 4 search input form.txt](https://github.com/inkline/inkline/files/11527553/Inkline.4.search.input.form.txt)


- I needed to replace `_text:primary` with `_color:primary`

**Comment by alexgrozav** [comment]
Hey! Should be fixed in 4.2.0. Can you please confirm?

**Comment by five1** [comment]
Hi. I tested version 4.2.2. Unfortunately, the clearable icon is still visible on initial load. Making the placeholder text null does not make any difference.

**Comment by five1** [comment]
Sorry, after some further testing with version 4.2.2 the clearable icon is not showing on initial load. This is the expected behaviour.

However, I have discovered three more issues:
- https://github.com/inkline/inkline/issues/384
- https://github.com/inkline/inkline/issues/385
- https://github.com/inkline/inkline/issues/386
